[project]
name = "geo-ftads"
version = "0.1.0"
description = "Geospatial fleet transition and decision support"
authors = ["Danika MacDonell <danikam@mit.edu>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[tasks]
runserver = "python manage.py runserver"

[dependencies]
django = ">=5.0.7,<6"
django-environ = ">=0.11.2,<0.12"
django-storages = ">=1.14.3,<2"
s3transfer = ">=0.10.2,<0.11"
boto3 = ">=1.34.150,<2"
botocore = ">=1.34.150,<2"
shapely = ">=2.0.5,<3"
